In [32]:
import tensorflow as tf
import numpy as np

In [14]:
sess = tf.Session();

## broadcasting
Tensorflow의 연산에서는 기본적으로 브로드캐스팅을 지원하기 때문에
shape를 신경써서 작성해야함

In [15]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
print(sess.run(matrix1 + matrix2))

[[4. 5.]]


In [16]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
print(sess.run(matrix1 + matrix2))

[[4. 6.]]


In [18]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
print(sess.run(matrix1 + matrix2))

[[4. 5.]
 [5. 6.]]


## Reduce mean
평균을 계산하는 메서드, 단위에 주의해야함

In [21]:
print(sess.run(tf.reduce_mean([1, 2], axis=0)))
print(sess.run(tf.reduce_mean([1., 2.], axis=0)))


1
1.5


In [24]:
x = [[1., 2.],
    [3., 4.]]

print(sess.run(tf.reduce_mean(x)))
print(sess.run(tf.reduce_mean(x, axis=0)))
print(sess.run(tf.reduce_mean(x, axis=1)))
print(sess.run(tf.reduce_mean(x, axis=-1)))

2.5
[2. 3.]
[1.5 3.5]
[1.5 3.5]


## Reduce sum
합 계산

In [27]:
print(sess.run(tf.reduce_sum(x)))
print(sess.run(tf.reduce_sum(x, axis=0)))
print(sess.run(tf.reduce_sum(x, axis=-1)))
print(sess.run(tf.reduce_mean(tf.reduce_sum(x, axis=-1))))


10.0
[4. 6.]
[3. 7.]
5.0


## Argmax
maximum 값의 위치

In [31]:
x = [[0, 1, 2],
    [2, 1, 0]]

print(sess.run(tf.argmax(x, axis=0)))
print(sess.run(tf.argmax(x, axis=1)))
print(sess.run(tf.argmax(x, axis=-1)))

[1 0 0]
[2 0]
[2 0]


## Reshape

가장 많이 쓰임

In [36]:
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
              
             [[6, 7, 8],
             [9, 10, 11]]])

t.shape

(2, 2, 3)

In [37]:
print(sess.run(tf.reshape(t, shape=[-1, 3])))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [38]:
print(sess.run(tf.reshape(t, shape=[-1, 1, 3])))

[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]


In [39]:
print(sess.run(tf.reshape(t, shape=[-1, 2])))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [40]:
print(sess.run(tf.squeeze([[0],[1],[2]])))

[0 1 2]


In [42]:
print(sess.run(tf.expand_dims([0, 1, 2], 1)))

[[0]
 [1]
 [2]]


## one hot

In [46]:
print(sess.run(tf.one_hot([[0], [1], [2], [0]], depth=3)))

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]]


In [54]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
print(sess.run(tf.reshape(t, shape=[-1, 3])))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


## Casting

In [61]:
print(sess.run(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32)))

[1 2 3 4]


In [62]:
print(sess.run(tf.cast([True, False], tf.int32)))

[1 0]


## Stack

In [66]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

print(sess.run(tf.stack([x, y, z])))
print(sess.run(tf.stack([x, y, z], axis=1)))

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


## Ones ans Zeros like

In [68]:
x = [[0, 1, 2],
    [2, 1, 0]]

print(sess.run(tf.ones_like(x)))

[[1 1 1]
 [1 1 1]]


In [69]:
print(sess.run(tf.zeros_like(x)))

[[0 0 0]
 [0 0 0]]


## Zip

In [70]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [71]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
