In [1]:
import tensorflow as tf

In [6]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [7]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [9]:
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1)) # 일치햐면 True 아니면 False
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [11]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 3.7930431 [[-1.0889597  -0.9651024   0.09782258]
 [-0.07201496 -1.2061116   0.32313263]
 [-1.2106395   0.98064667 -0.5428596 ]]
1 2.9778538 [[-1.0652508  -0.9896661   0.09867736]
 [ 0.08744545 -1.2887764   0.24633713]
 [-1.0499101   0.87345606 -0.59639835]]
2 2.1901734 [[-1.0436834  -1.0087041   0.09614795]
 [ 0.24003914 -1.343407    0.14837414]
 [-0.8940223   0.7924564  -0.67128646]]
3 1.5207593 [[-1.0316292  -1.0262285   0.10161817]
 [ 0.34574863 -1.3930726   0.0923302 ]
 [-0.77592295  0.7155816  -0.71251106]]
4 1.3085049 [[-1.0422393  -1.0308867   0.11688641]
 [ 0.32359856 -1.3723636   0.0937712 ]
 [-0.771544    0.7072383  -0.70854676]]
5 1.2936058 [[-1.049825   -1.0369358   0.13052125]
 [ 0.31792152 -1.3594497   0.08653445]
 [-0.7524071   0.6913662  -0.71181154]]
6 1.2797675 [[-1.058557   -1.0423206   0.14463826]
 [ 0.30520856 -1.3429239   0.08272152]
 [-0.73999405  0.67921144 -0.7120698 ]]
7 1.2663188 [[-1.0666155  -1.0480002   0.15837635]
 [ 0.29574955 -1.3281126   0.0773693 ]
